name: Run Gradle check

on:
  push:
    branches:
      - master
      - releases/*

jobs:
  gradle-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    - uses: eskatos/gradle-command-action@v2
      name: gradle check
      with:
        arguments: check
